### ISSUE TITLE
improvements

### ISSUE THREAD

**Issue by foodtourama** [instabotai/tiktok-api#10]
Hi!
First of all, great code! Simple and it works without weird plug-ins (can run code on Asus router).
I must say I'm new to python but not to coding. I did some minor improvements but don't know how to submit the changes I did, I've never used github... (I can send them via email for you to verify, maybe?) Anyways... two questions/requests:
- Sometimes I receive "Response 403" when trying to download videos without watermark, is there a way to default the download to the watermarked version if this happens? (one of the improvements I did was to only download videos with Response 200)
- The other thing is, for accounts that have more that ~21 videos (the first page you scrape)... is it necessary to use a headless browser like selenium or something to fake the scrolling and get all video links? Is there another way or maybe a lightweight headless browser?
Thank you very much for you time!

**Comment by reliefs** [comment]
You can fork it and do a pull request.
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

1. Most likely the endpoints need to be updated.

2. Maybe, selenium is not a option because i want this api to work without browser to it can be implemented into other packages without "browsers" running.

**Comment by reliefs** [comment]
Update: 
I have no issues with download without watermark.. have you tried another user or the default user ?
